### ISSUE TITLE
Floating point numbers ending with decimal point are parsed as int

### ISSUE THREAD

**Issue by Zueuk** [mvhooren/JitCat#4]
Expression `1.` produces an int, should be float

**Comment by mvhooren** [comment]
> Expression `1.` produces an int, should be float

`1.` will actually produce a parsing error. Still not the expected behaviour though.

**Comment by Zueuk** [comment]
I'd say this shouldn't be an error, things like `1.` in C++ code are perfectly fine.
Besides it's a common way to tell floating point numbers from integers.

**Comment by mvhooren** [comment]
Yes, I agree `1.` should be parsed as a float.

**Comment by mvhooren** [comment]
This has now been fixed, as well as several other problems with floating point parsing such as `.0` and `1e10`

**Comment by Zueuk** [comment]
I still managed to break your parser :) try `1.-1`

**Comment by mvhooren** [comment]
> I still managed to break your parser :) try `1.-1`

This one should also be fixed now.
