### ISSUE TITLE
Unnecessary if's in CatFunctionCall::execute()

### ISSUE THREAD

**Issue by Zueuk** [mvhooren/JitCat#7]
I wanted to add more trigonometric functions, and noticed this:
```
case CatBuiltInFunctionType::Sin:
    if (argumentTypes[0].isFloatType())
    {
        return (float)std::sin(std::any_cast<float>(argumentValues[0]));
    }
    else
    {
        return (float)std::sin((float)std::any_cast<int>(argumentValues[0]));
    }
```
happening _a lot_.

As I understand, this branching would make sense if return type depended on the argument type(s), but in many cases the result is always float - so the only problem is converting type of the argument value - and I see that there is a `CatGenericType::convertToFloat()`, that seems to do exactly that.

Wouldn't be better to rewrite these functions like this:
```
case CatBuiltInFunctionType::Sin:
    return (float)std::sin(CatGenericType::convertToFloat(argumentValues[0], argumentTypes[0]));
```

**Comment by mvhooren** [comment]
Yes that would be better. Feel free to submit a pull request for those extra trigonometric functions if you want.

I plan on making it easier in the future to add functions like this through reflection of static C++ functions. This is already partially implemented in the newLanguageFeatures branch. It will eventually replace the CatBuiltInFunctionCall AST node in its entirety.
