### ISSUE TITLE
Found abs() being tested instead of tan()

### ISSUE THREAD

**Issue by Zueuk** [mvhooren/JitCat#8]
```
SECTION("Tan_obj")
{
    Expression<float> testExpression(&context, "abs(nestedObject)");
    doChecks(0.0f, true, false, false, testExpression, context);
}
```

Won't be surprized if there's more, that Tests.cpp is way too big...

**Comment by mvhooren** [comment]
Yes, Tests.cpp needs to be split up. It is one of the things on top of my to-do list :)
There might be a few more copy-paste mistakes like this. Will check when I get to splitting up that file.
